import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { SpreadsheetRecord } from '../../models/spreadsheet-record';

@Injectable({
  providedIn: 'root'
})
export class SpreadsheetService {

  records = [
    {
      'unique_id': 1111,
      'Division': 'Southwest',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 2835,
      'Street Address': '3325 N Hunt Highway',
      'City': 'Florence',
      'ST': 'AZ',
      'ZIP': 85132,
      'Latitude': 33.0626,
      'Longitude': -111.4837
    },
    {
      'unique_id': 123,
      'Division': 'Denver',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 1877,
      'Street Address': '880 South Perry St',
      'City': 'Castle Rock',
      'ST': 'CO',
      'ZIP': 80104,
      'Latitude': 39.3619,
      'Longitude': -104.8608
    },
    {
      'unique_id': 30,
      'Division': 'Southwest',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 3941,
      'Street Address': '5040 W Cactus',
      'City': 'Glendale',
      'ST': 'AZ',
      'ZIP': 85304,
      'Latitude': 33.5978,
      'Longitude': -112.1671
    },
    {
      'unique_id': 1405,
      'Division': 'Acme',
      'Banner': 'Acme',
      'store_id': '',
      'New Store #': 2424,
      'Street Address': '100 Route 22',
      'City': 'Goldens Bridge',
      'ST': 'NY',
      'ZIP': 10536,
      'Latitude': 41.2933,
      'Longitude': -73.676
    },
    {
      'unique_id': 154,
      'Division': 'Denver',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 892,
      'Street Address': '3840 East 104th Avenue',
      'City': 'Thornton',
      'ST': 'CO',
      'ZIP': 80233,
      'Latitude': 39.8833,
      'Longitude': -104.9427
    },
    {
      'unique_id': 685,
      'Division': 'SoCal',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 2558,
      'Street Address': '33601 Del Obispo',
      'City': 'Dana Point',
      'ST': 'CA',
      'ZIP': 92629,
      'Latitude': 33.4751,
      'Longitude': -117.6862
    },
    {
      'unique_id': 399,
      'Division': 'Southern',
      'Banner': 'Tom Thumb',
      'store_id': '',
      'New Store #': 3625,
      'Street Address': '302 South Park Blvd',
      'City': 'Grapevine',
      'ST': 'TX',
      'ZIP': 76051,
      'Latitude': 32.9388,
      'Longitude': -97.0972
    },
    {
      'unique_id': 809,
      'Division': 'SoCal',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 1105,
      'Street Address': '8880 Valley View Street',
      'City': 'Buena Park',
      'ST': 'CA',
      'ZIP': 90620,
      'Latitude': 33.8341,
      'Longitude': -118.0272
    },
    {
      'unique_id': 1295,
      'Division': 'Southwest',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 261,
      'Street Address': '101 Naco Highway',
      'City': 'Bisbee',
      'ST': 'AZ',
      'ZIP': 85603,
      'Latitude': 31.4011,
      'Longitude': -109.9172
    },
    {
      'unique_id': 94,
      'Division': 'Denver',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 1873,
      'Street Address': '771 Thornton Parkway',
      'City': 'Thornton',
      'ST': 'CO',
      'ZIP': 80229,
      'Latitude': 39.8724,
      'Longitude': -104.9759
    },
    {
      'unique_id': 1287,
      'Division': 'Portland',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 1665,
      'Street Address': '1705 S Hwy 97',
      'City': 'Redmond',
      'ST': 'OR',
      'ZIP': 97756,
      'Latitude': 44.2607,
      'Longitude': -121.1794
    },
    {
      'unique_id': 572,
      'Division': 'Acme',
      'Banner': 'Acme',
      'store_id': '',
      'New Store #': 3753,
      'Street Address': '700 W Lancaster Ave',
      'City': 'Wayne',
      'ST': 'PA',
      'ZIP': 19333,
      'Latitude': 40.0454,
      'Longitude': -75.4077
    },
    {
      'unique_id': 1171,
      'Division': 'Shaws',
      'Banner': 'Shaws',
      'store_id': '',
      'New Store #': 4481,
      'Street Address': '28 Woodbury Ave',
      'City': 'Portsmouth',
      'ST': 'NH',
      'ZIP': 3801,
      'Latitude': 43.0889,
      'Longitude': -70.7937
    },
    {
      'unique_id': 1071,
      'Division': 'Denver',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 824,
      'Street Address': '4909 E Main',
      'City': 'Farmington',
      'ST': 'NM',
      'ZIP': 87402,
      'Latitude': 36.7659,
      'Longitude': -108.1464
    },
    {
      'unique_id': 1255,
      'Division': 'SoCal',
      'Banner': 'Vons',
      'store_id': '',
      'New Store #': 1738,
      'Street Address': '729 North H St',
      'City': 'Lompoc',
      'ST': 'CA',
      'ZIP': 93436,
      'Latitude': 34.6496,
      'Longitude': -120.4592
    },
    {
      'unique_id': 1087,
      'Division': 'Denver',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 2341,
      'Street Address': '620 West Platte Ave',
      'City': 'Fort Morgan',
      'ST': 'CO',
      'ZIP': 80701,
      'Latitude': 40.2557,
      'Longitude': -103.8167
    },
    {
      'unique_id': 1297,
      'Division': 'Seattle',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 1833,
      'Street Address': '1313 Meals Ave',
      'City': 'Valdez',
      'ST': 'AK',
      'ZIP': 99686,
      'Latitude': 61.1311,
      'Longitude': -146.3488
    },
    {
      'unique_id': 754,
      'Division': 'Seattle',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 402,
      'Street Address': '1450 SW Erie St',
      'City': 'Oak Harbor',
      'ST': 'WA',
      'ZIP': 98277,
      'Latitude': 48.2865,
      'Longitude': -122.6614
    },
    {
      'unique_id': 118,
      'Division': 'Denver',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 885,
      'Street Address': '323 S Broadway',
      'City': 'Denver',
      'ST': 'CO',
      'ZIP': 80209,
      'Latitude': 39.7107,
      'Longitude': -104.9889
    },
    {
      'unique_id': 766,
      'Division': 'InterMtn',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 897,
      'Street Address': '2512 Broadway',
      'City': 'Grand Junction',
      'ST': 'CO',
      'ZIP': 81507,
      'Latitude': 39.0669,
      'Longitude': -108.5886
    },
    {
      'unique_id': 133,
      'Division': 'Denver',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 862,
      'Street Address': '3660 S Mason St',
      'City': 'Fort Collins',
      'ST': 'CO',
      'ZIP': 80525,
      'Latitude': 40.5366,
      'Longitude': -105.0779
    },
    {
      'unique_id': 825,
      'Division': 'SoCal',
      'Banner': 'Vons',
      'store_id': '',
      'New Store #': 3329,
      'Street Address': '2010 Cliff Dr',
      'City': 'Santa Barbara',
      'ST': 'CA',
      'ZIP': 93109,
      'Latitude': 34.4025,
      'Longitude': -119.7238
    },
    {
      'unique_id': 881,
      'Division': 'SoCal',
      'Banner': 'Lucky\'s',
      'store_id': '',
      'New Store #': 227,
      'Street Address': '351 Wake Ave',
      'City': 'El Centro',
      'ST': 'CA',
      'ZIP': 92243,
      'Latitude': 32.7703,
      'Longitude': -115.5504
    },
    {
      'unique_id': 1230,
      'Division': 'SoCal',
      'Banner': 'Vons',
      'store_id': '',
      'New Store #': 2007,
      'Street Address': '431 E Arrow Hwy',
      'City': 'Glendora',
      'ST': 'CA',
      'ZIP': 91740,
      'Latitude': 34.1078,
      'Longitude': -117.8564
    },
    {
      'unique_id': 80,
      'Division': 'Denver',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 879,
      'Street Address': '4405 Centennial Blvd',
      'City': 'Colorado Springs',
      'ST': 'CO',
      'ZIP': 80907,
      'Latitude': 38.8949,
      'Longitude': -104.8499
    },
    {
      'unique_id': 91,
      'Division': 'Denver',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 881,
      'Street Address': '500 E 120Th Ave',
      'City': 'Northglenn',
      'ST': 'CO',
      'ZIP': 80233,
      'Latitude': 39.9123,
      'Longitude': -104.9809
    },
    {
      'unique_id': 149,
      'Division': 'Denver',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 804,
      'Street Address': '1451 W Eisenhower Blvd',
      'City': 'Loveland',
      'ST': 'CO',
      'ZIP': 80537,
      'Latitude': 40.4085,
      'Longitude': -105.0981
    },
    {
      'unique_id': 1173,
      'Division': 'Shaws',
      'Banner': 'Star Markets Inc.',
      'store_id': '',
      'New Store #': 1430,
      'Street Address': '65 Main St',
      'City': 'Medway',
      'ST': 'MA',
      'ZIP': 2053,
      'Latitude': 42.152,
      'Longitude': -71.4032
    },
    {
      'unique_id': 378,
      'Division': 'Southern',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 4239,
      'Street Address': '921 Westgate Way',
      'City': 'Wylie',
      'ST': 'TX',
      'ZIP': 75098,
      'Latitude': 33.0065,
      'Longitude': -96.55206955
    },
    {
      'unique_id': 124,
      'Division': 'Denver',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 839,
      'Street Address': '8434 South Kipling Parkway',
      'City': 'Littleton',
      'ST': 'CO',
      'ZIP': 80127,
      'Latitude': 39.5634,
      'Longitude': -105.1075
    },
    {
      'unique_id': 1428,
      'Division': 'Denver',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 2895,
      'Street Address': '7450 South University',
      'City': 'Centennial',
      'ST': 'CO',
      'ZIP': 80122,
      'Latitude': 39.5816,
      'Longitude': -104.9576
    },
    {
      'unique_id': 283,
      'Division': 'Eastern',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 1084,
      'Street Address': '30 Pidgeon Hill',
      'City': 'Sterling',
      'ST': 'VA',
      'ZIP': 20165,
      'Latitude': 39.0373,
      'Longitude': -77.4122
    },
    {
      'unique_id': 1530,
      'Division': 'Eastern',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 1759,
      'Street Address': '22350 Sterling Boulevard',
      'City': 'Sterling Park',
      'ST': 'VA',
      'ZIP': 20164,
      'Latitude': 38.9975,
      'Longitude': -77.409
    },
    {
      'unique_id': 1735,
      'Division': 'Denver',
      'Banner': 'Albertsons',
      'store_id': '',
      'New Store #': 816,
      'Street Address': '1601 Highway 50 West',
      'City': 'Pueblo',
      'ST': 'CO',
      'ZIP': 81008,
      'Latitude': 38.311,
      'Longitude': -104.6279
    },
    {
      'unique_id': 2102,
      'Division': 'Eastern',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 1281,
      'Street Address': '10000 Balt Ntl Pike',
      'City': 'Ellicott City',
      'ST': 'MD',
      'ZIP': 21042,
      'Latitude': 39.2801,
      'Longitude': -76.858
    },
    {
      'unique_id': 2107,
      'Division': 'Eastern',
      'Banner': 'Safeway',
      'store_id': '',
      'New Store #': 105,
      'Street Address': '10 King St',
      'City': 'Waldorf',
      'ST': 'MD',
      'ZIP': 20602,
      'Latitude': 38.6018,
      'Longitude': -76.9036
    },
    {
      'unique_id': 2216,
      'Division': 'Shaws',
      'Banner': 'Star Markets Inc.',
      'store_id': '',
      'New Store #': 2576,
      'Street Address': '33 Kilmarnock Street',
      'City': 'Boston',
      'ST': 'MA',
      'ZIP': 2215,
      'Latitude': 42.3435,
      'Longitude': -71.1005
    },
    {
      'unique_id': 2217,
      'Division': 'Shaws',
      'Banner': 'Star Markets Inc.',
      'store_id': '',
      'New Store #': 3588,
      'Street Address': '1065 Commonwealth Ave',
      'City': 'Boston',
      'ST': 'MA',
      'ZIP': 2215,
      'Latitude': 42.3527,
      'Longitude': -71.1234
    },
    {
      'unique_id': 2218,
      'Division': 'Shaws',
      'Banner': 'Star Markets Inc.',
      'store_id': '',
      'New Store #': 2565,
      'Street Address': '699 Mt Auburn Street',
      'City': 'Cambridge',
      'ST': 'MA',
      'ZIP': 2138,
      'Latitude': 42.3753,
      'Longitude': -71.149
    },
    {
      'unique_id': 2219,
      'Division': 'Shaws',
      'Banner': 'Star Markets Inc.',
      'store_id': '',
      'New Store #': 4589,
      'Street Address': '20 Sidney Street',
      'City': 'Cambridge',
      'ST': 'MA',
      'ZIP': 2139,
      'Latitude': 42.3619,
      'Longitude': -71.0999
    },
    {
      'unique_id': 2220,
      'Division': 'Shaws',
      'Banner': 'Star Markets Inc.',
      'store_id': '',
      'New Store #': 604,
      'Street Address': '4 River Street',
      'City': 'Dorchester',
      'ST': 'MA',
      'ZIP': 2124,
      'Latitude': 42.2719,
      'Longitude': -71.0699
    },
    {
      'unique_id': 2221,
      'Division': 'Shaws',
      'Banner': 'Star Markets Inc.',
      'store_id': '',
      'New Store #': 2575,
      'Street Address': '275 Beacon Street',
      'City': 'Somerville',
      'ST': 'MA',
      'ZIP': 2143,
      'Latitude': 42.3836,
      'Longitude': -71.1117
    },
    {
      'unique_id': 2222,
      'Division': 'Shaws',
      'Banner': 'Star Markets Inc.',
      'store_id': '',
      'New Store #': 3580,
      'Street Address': '14 McGrath Highway',
      'City': 'Somerville',
      'ST': 'MA',
      'ZIP': 2143,
      'Latitude': 42.3741,
      'Longitude': -71.0839
    },
    {
      'unique_id': 2248,
      'Division': 'Southern',
      'Banner': 'Tom Thumb',
      'store_id': '',
      'New Store #': 3641,
      'Street Address': '3411 Custer Pkwy',
      'City': 'Richardson',
      'ST': 'TX',
      'ZIP': 75080,
      'Latitude': 32.9966,
      'Longitude': -96.7295
    },
    {
      'unique_id': 2257,
      'Division': 'United',
      'Banner': 'United',
      'store_id': '',
      'New Store #': 3530,
      'Street Address': '3552 S Soncy Rd',
      'City': 'Amarillo',
      'ST': 'TX',
      'ZIP': 79119,
      'Latitude': 35.1708372,
      'Longitude': -101.9410296
    }
  ];

  constructor() {
  }

  loadSpreadsheet(): Observable<SpreadsheetRecord[]> {
    return of(this.records.map(r => new SpreadsheetRecord(r['unique_id'], r['Latitude'], r['Longitude'], r['Banner'])));
  }
}
